name: Build Theme

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Bundle UI
      run: |
        npm install
        gulp bundle
    - name: Commit files
      run: |
        git config --global user.name 'Neetu'
        git config --global user.email 'shabnikkigoyal@gmail.com'
        git add -f build
        git commit -m "Bundle UI"
        git push origin
