name: Build Theme

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Bundle UI
      run: |
        npm install        
        gulp bundle
        
    - name: Commit files
      run: |
        git config --global user.name 'Neetu'
        git config --global user.email 'shabnikkigoyal@gmail.com'
        git add -f build
        git commit -m "Bundle UI"
        git push origin
